export { default as Footer } from './Footer';
export { default as Hero } from './Hero'
export { default as Destinations } from './Destinations';
export { default as Navbar } from './Navbar'
export { default as Search } from './Search';
export { default as Selects } from './Selects'
export { default as Carousel } from './Carousel'
export { default as ContactUsPage } from './ContactUs/ContactUsPage'
export { default as TnC } from './TermsPage/TnC'
